title: unkovsky.space
github_username: niihelium
github_url: http://github.com/niihelium
highlighter: rouge
permalink: /:year/:month/:day/:title/
year: 2019
description: Nikita Unkovsky
url: http://unkovsky.space
encoding: UTF-8

kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
sass:
  sass_dir: ./assets/css

paginate: 6
paginate_path: /page/:num/